### ISSUE TITLE
Building Problems with Visual Studio 2019

### ISSUE THREAD

**Issue by Schafwolle** [daniel-lerch/vocup#28]
Hy 
I tried to build the current avalonia branch. I have installed Visual Studio 2019 and opened the solution checked in. 
Then I tried to build the debug version of the entire solution. The build failes with:

~~~
Ungültige ResX-Datei. Der angeforderte Wert "Ctrl" konnte nicht gefunden werden. Zeile 181, Position 5.	Vocup	
~~~

After that I tried to change the language to english. Now the following error occure:

~~~
No certificate found with the supplied thumbprint: 9C503A44C755504352901E2766267CEA3C7FAA82	Vocup.Packaging	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	826	
~~~

I hope that this not a stupid mistake on my side. I know how to program in C# but when it comes to GUIs and XAML, I am lost.

**Comment by daniel-lerch** [comment]
You don't need to build the entire solution to work on Vocup 2.0. The projects `Vocup` and `Vocup.Packaging` contain the code of Vocup 1.X. I kept them there because that's more convenient than changing branches all the time. You can just build an run `Vocup.Windows` which references `Vocup.Avalonia` and `Vocup.Core` where all the new code is located.

However, everyone should be able to build and debug the current version, too. I haven't been using a German localization of Visual Studio anymore for many years now but I'm not surprised to see more errors with Windows Forms key bindings. Maybe I should add a notice for that to the README.

To resolve the second error just remove the section `<PackageCertificateThumbprint>` from `Vocup.Packaging.wapproj`. This certificate is only required for Microsoft Store submission but I was tired of creating new certificates for every release so just committed that line 😅

**Comment by Schafwolle** [comment]
Building only "Vocup.Windows" works.

I normally use English localization for my development tools but only German was installed. So I first tried it with German.
